name: GL-INET B1300 OpenWrt Build

on:
  push:
    paths:
      - 'CHANGELOG.md'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@master
        with:
          ref: master
      - name: Initialize Environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo apt-get update
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android/sdk
          sudo docker image prune -a -f
          sudo apt-get -y install unzip subversion
          sudo apt-get -y purge dotnet* ghc* google* llvm* mysql* php* zulu* firefox hhvm
          sudo apt-get -y autoremove --purge
          sudo apt-get -y install build-essential asciidoc binutils bzip2  \
          gawk gettext git libncurses5-dev libz-dev patch python3 python2.7  \
          unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs \
          git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo  \
          libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake \
          libtool autopoint device-tree-compiler g++-multilib antlr3 gperf \
          wget curl swig rsync
      - name: Download Source
        run: |
          git clone https://github.com/coolsnowwolf/lede openwrt
          
      - name: Update Feeds		
        run: |		
          cd openwrt	
          ./scripts/feeds update -a		
          ./scripts/feeds install -a
      - name: Custom Configure Files		
        run: |		
          cp b1300_config openwrt/.config

      - name: Make Configure Files		
        run: |		
          cd openwrt
          make defconfig
          
      - name: Download		
        run: |
          cd openwrt
          make -j8 download V=s

      - name: Compile OpenWrt
        run: |
          cd openwrt
          make -j1 V=s

      - name: Assemble Artifact
        run: |
          rm -rf ./artifact/
          mkdir -p ./artifact/
          cp openwrt/out/*.img.zip ./artifact/
          cp openwrt/.config ./artifact/

      - name: Upload Artifact
        uses: actions/upload-artifact@master
        with:
          name: GL-INET B1300 Openwrt
          path: ./artifact/
          
      